# Generated by Django 5.2.3 on 2025-06-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneDriveImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('parent_id', models.CharField(blank=True, max_length=200, null=True)),
                ('full_path', models.TextField(blank=True, null=True)),
                ('thumbnail_url', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('embedding', models.BinaryField(blank=True, null=True)),
                ('last_scanned', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
